// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amnctyivayvpzmgjqyyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbmN0eWl2YXl2cHptZ2pxeXlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMDE2OTgsImV4cCI6MjA2MDY3NzY5OH0.cpUX0U_ZSL-0BkmxZiWgAbvhoT4PIfB6_Zhdysbefgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);